"""drop index, create unique constraint

Revision ID: 9a7d5aac733d
Revises: 7f9332f97ad9
Create Date: 2026-04-09 22:40:41.296600

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a7d5aac733d"
down_revision: Union[str, Sequence[str], None] = "7f9332f97ad9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_listings_external_id"), table_name="listings")
    op.create_unique_constraint(
        "uq_source_external_id", "listings", ["source", "external_id"]
    )
    op.create_unique_constraint(None, "listings", ["external_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "listings", type_="unique")
    op.drop_constraint("uq_source_external_id", "listings", type_="unique")
    op.create_index(
        op.f("ix_listings_external_id"), "listings", ["external_id"], unique=True
    )
    # ### end Alembic commands ###
